#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Xresources
if [ -f $XDG_CONFIG_HOME/X11/Xresources ]; then
    /usr/bin/xrdb $XDG_CONFIG_HOME/X11/Xresources
fi

# Set screen resolution
xrandr --output VIRTUAL1 --off --output DP1 --off --output HDMI1 --off --output VGA-1-2 --off --output VGA1 --off --output LVDS1 --off --output eDP1 --mode 1920x1080 --primary --pos 0x0 --rotate normal

# Enable defaults
numlockx &
setxkbmap -option caps:swapescape &
synclient VertEdgeScroll=0 &

# Enable lock on suspend
xss-lock --transfer-sleep-lock -- $XDG_CONFIG_HOME/scripts/lock.sh --nofork &

# Execute background applications
# -> Refer to i3 config file

# Execute window manager
exec i3
